### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vladshcherbin**

### CODE REVIEW

**Comment by ryanswapp** [comment]
Ahh nice catch! Thanks for helping out with that. Do we need the plain `mix` after `mix deps.get` ?Other than that it looks good.

**Comment by vladshcherbin** [comment]
Yes, the `mix deps.get` will get the packages and `mix` will compile.

**Comment by ryanswapp** [comment]
True. I just never type plain `mix` because `mix phoenix.server` will take care of the compile step and I'd rather just type one command. Matter of preference I suppose. I'd like to keep the commands to as few as possible. Is there any compelling reason for keeping it in there?

**Comment by vladshcherbin** [comment]
Sure, we can remove. Give me one minute ;)

**Pull request closed without merging**
